# Generated by Django 2.1.5 on 2019-02-13 09:23

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rezervace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Jakou_učebnu', models.CharField(choices=[('Učebna A', 'Učebna A'), ('Učebna B', 'Učebna B'), ('Učebna C', 'Učebna C')], max_length=20)),
                ('Začátek_pronájmu_učebny', models.DateTimeField()),
                ('Konec_pronájmu_učebny', models.DateTimeField()),
                ('Email', models.EmailField(max_length=254)),
                ('Telefonní_číslo', models.IntegerField()),
                ('Počet_účastníků', models.IntegerField()),
                ('Občerstvení', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Slaný', 'Slaný'), ('Sladký', 'Sladký'), ('Smíšený', 'Smíšený'), ('Celodenní balíček', 'Celodenní balíček')], max_length=38)),
                ('Poznámka', models.TextField(blank=True)),
            ],
        ),
    ]
