# Generated by Django 2.1.5 on 2019-02-13 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rezervace', '0002_rezervace_objednávka_zadána'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rezervace',
            old_name='Objednávka_zadána',
            new_name='Objednávka_přijata',
        ),
    ]
