# Generated by Django 2.1.5 on 2019-02-25 08:37

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rezervace', '0004_auto_20190215_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='rezervace',
            name='Společnost',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rezervace',
            name='Občerstvení',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Tento základní balíček je účtovaný automaticky - (Káva, voda, čaj, ovocné sirupy)', 'Tento základní balíček je účtovaný automaticky - (Káva, voda, čaj, ovocné sirupy)'), ('Slaný', 'Slaný'), ('Sladký', 'Sladký'), ('Smíšený', 'Smíšený'), ('Celodenní balíček', 'Celodenní balíček')], default='Tento základní balíček je účtovaný automaticky - (Káva, voda, čaj, ovocné sirupy)', max_length=120),
        ),
    ]
